language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.2
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
