language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - chmod 777 -R storage
  - cp .env.travis .env
  - php artisan key:generate
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit